# Generated by Django 5.0.2 on 2024-02-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discount",
            name="discount_rate",
        ),
        migrations.RemoveField(
            model_name="discount",
            name="price",
        ),
        migrations.AddField(
            model_name="discount",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
