# Generated by Django 5.0.2 on 2024-02-29 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Discount",
        ),
    ]
