# Generated by Django 5.0.2 on 2024-02-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_delete_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
