# Generated by Django 5.0.2 on 2024-02-27 17:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "product",
            "0002_remove_discount_discount_rate_remove_discount_price_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discount",
            options={
                "verbose_name": "Offer Product",
                "verbose_name_plural": "Offer Products",
            },
        ),
        migrations.RemoveField(
            model_name="discount",
            name="discount_amount",
        ),
        migrations.AddField(
            model_name="discount",
            name="discount",
            field=models.IntegerField(
                default=0,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(99),
                ],
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="discount_price",
            field=models.IntegerField(
                null=True, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_offers",
                to="product.product",
            ),
        ),
    ]
