# Generated by Django 5.0.2 on 2024-02-27 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_viewedproduct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="viewedproduct",
            name="viewed_at",
            field=models.DateTimeField(default=datetime.timezone),
        ),
    ]
