# Generated by Django 5.0.2 on 2024-02-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_remove_product_discount_price_product_discount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
