# Generated by Django 5.0.2 on 2024-02-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_alter_product_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="available",
            field=models.BooleanField(),
        ),
    ]
