# Generated by Django 5.0.2 on 2024-02-28 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notifications",
            name="user",
        ),
    ]
