# Generated by Django 5.0.2 on 2024-02-29 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0003_notification_delete_notifications"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="created_at",
        ),
    ]
