# Generated by Django 5.0.2 on 2024-02-29 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0004_remove_notification_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="user",
        ),
    ]
