# Generated by Django 5.0.2 on 2024-02-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0005_remove_notification_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="viewed",
            field=models.BooleanField(default=False),
        ),
    ]
