# Generated by Django 5.0.2 on 2024-02-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="chat",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
