# Generated by Django 5.0.2 on 2024-02-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="code",
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
