# Generated by Django 5.0.2 on 2024-02-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profiles", "0002_alter_customuser_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellerprofile",
            name="facebook_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="tiktok_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="whatsapp_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
